### ISSUE TITLE
Clock in/out functionality

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/climesync#125]
Climesync should have a feature to clock in and out when working on a specific project and/or activity. The workflow might look like this:
- Clock in command
- Input project
- Optionally input activities and issue URI
- Do work
- Clock out command
- Input activities and issue URI if didn't before
- Input notes

After that, Climesync will submit the time to the TimeSync server.

Climesync should keep track of total time even if the user quits and restarts the program. It might use some sort of file to do this (maybe located somewhere like `~/.climesync.d/.clock/`). It might also provide some sort of indicator on the Climesync prompt to indicate whether the user is currently clocked in on a project.

**Comment by pop** [comment]
This is a good idea, it could definitely be a _killer feature_ for climesync.  It deserves some thought.

### Questions:
- When happens when you submit time for different project wile clocked in already (logging time for two projects at once, maybe even for the same time-frame).  Is this allowed?  If not, how is this enforced?
- (How) will you be able to retro-actively force an end-time?  I for one guarantee I'll forget to clock out _most_ of the time.
- Will I be able to check the time before submitting it?

### Suggestions

First off, I'd expect the clock-in behavior to act like this:

```
$ climesync clock-in
Project: ...
Activity: ...
URI: ...
Notes: ...
```

and the clock-out behavior to act like this:

```
$ climesync clock-out
Your time:
  Duration: AA:BB:CC
  Date: XX-YY-ZZZZ
  ...
Does this look right? [Y/n] n
Duration [AA:BB:CC]
Date [XX-YY-ZZZZ]
... ( Goes into edit-time routine )
```
- Include an optional `-y` flag to skip the review phase of clocking out (outlined above).
- Print out the time after it's submitted, with a `-q` flag to suppress that behavior.
- Optionally we could include the `--project, --uri, --activity...` flags to (either/or/both) of the `clock-in` and `clock-out` sub-commands.

**Comment by aaroncohen73** [comment]
@ElijahCaine 

The way that I see the clock in/out commands functioning is that clocking in creates a session (stored in a file?) that contains information such as the date and time that the user clocked in (maybe stored as UTC so we don't have to deal with DST/timezones) and any extra information that the user entered at clock-in (project, activities, etc.). If the user tries to clock in again while already clocked in then Climesync will see the existing session and refuse to clock in, since it doesn't make sense to be working on two separate projects at once.

When the user clocks out, then information from that session is read, the user is given the opportunities to make changes or corrections, and then it's sent off to TimeSync. If the user forgets to clock out, then the duration of the time entry could be corrected here. If the date is different between clock-in and clock-out, then I think that it makes most sense to use the clock-in date. This could be up for debate though.

@Kennric What are your thoughts on this feature?
